parameters:
    ezplatform.cron.registry.cronjobs.class: Ibexa\Bundle\Cron\Registry\CronJobsRegistry

services:
    _defaults:
        autowire: true
        autoconfigure: true

    ezplatform.cron.registry.cronjobs:
        class: '%ezplatform.cron.registry.cronjobs.class%'
        lazy: true
        arguments:
            - '%kernel.environment%'
            - '@ezpublish.siteaccess'

    Ibexa\Bundle\Cron\Command\CronRunCommand:
        arguments:
            $logger: '@monolog.logger.cronjob'
            $cronJobsRegistry: '@ezplatform.cron.registry.cronjobs'
        tags:
            - { name: 'console.command' }
